In [2]:
import numpy as np
a = np.array([[4,3],[6,9]])  
b = np.array([[-2,9],[-5,2]])  
c=a-b
print c


[[ 6 -6]
 [11  7]]


In [24]:
import numpy as np
a = np.array([[2],[7],[4],[1]])
b=(1.0/2)*(a.astype(float))
print b

[[1. ]
 [3.5]
 [2. ]
 [0.5]]


In [20]:
import numpy as np
a = np.array([[8],[1],[4]])
print(a.shape)
b=a.T
print b.shape
print a.T



(3L, 1L)
(1L, 3L)
[[8 1 4]]


In [26]:
import numpy as np
u=np.array([1,3,-1])
v=np.array([2,2,4])
ans=u.T*v
print ans

[ 2  6 -4]


In [51]:
print("Let A and B be 3X3 (square) matrices. \n Which of the following must necessarily hold true?\n\na. A*B = B*A \nb. If B is a 3X3 identity matrix, then A*B = B*A\nc. (A*B)*A = A*(B*A)\nd. If C = A*B, then C is a 6*6 matrix. ")
print("\n\n")
print "Answers =\n b. If B is a 3X3 identity matrix, then A*B = B*A \nand\nc. (A*B)*A = A*(B*A) "

Let A and B be 3X3 (square) matrices. 
 Which of the following must necessarily hold true?

a. A*B = B*A 
b. If B is a 3X3 identity matrix, then A*B = B*A
c. (A*B)*A = A*(B*A)
d. If C = A*B, then C is a 6*6 matrix. 



Answers =
 b. If B is a 3X3 identity matrix, then A*B = B*A 
and
c. (A*B)*A = A*(B*A) 
